export const CONCEPT_CREATED = 'CONCEPT_CREATED'
export const CONCEPT_UPDATED = 'CONCEPT_UPDATED'
export const CONCEPT_DELETED = 'CONCEPT_DELETED'
export const MANY_CONCEPTS_DELETED = 'MANY_CONCEPTS_DELETED'
export const MANY_CONCEPTS_UPDATED = 'MANY_CONCEPTS_UPDATED'

export const CONCEPT_LINK_CREATED = 'CONCEPT_LINK_CREATED'
export const CONCEPT_LINK_DELETED = 'CONCEPT_LINK_DELETED'

export const GOAL_LINK_CREATED = 'GOAL_LINK_CREATED'
export const GOAL_LINK_DELETED = 'GOAL_LINK_DELETED'

export const OBJECTIVE_LINK_CREATED = 'OBJECTIVE_LINK_CREATED'
export const OBJECTIVE_LINK_DELETED = 'OBJECTIVE_LINK_DELETED'

export const COURSE_CREATED = 'COURSE_CREATED'
export const COURSE_UPDATED = 'COURSE_UPDATED'
export const COURSE_DELETED = 'COURSE_DELETED'

export const COURSE_LINK_CREATED = 'COURSE_LINK_CREATED'
export const COURSE_LINK_UPDATED = 'COURSE_LINK_UPDATED'
export const COURSE_LINK_DELETED = 'COURSE_LINK_DELETED'

export const WORKSPACE_UPDATED = 'WORKSPACE_UPDATED'
export const WORKSPACE_DELETED = 'WORKSPACE_DELETED'

export const PROJECT_WORKSPACE_DELETED = 'PROJECT_WORKSPACE_DELETED'
export const PROJECT_WORKSPACE_CREATED = 'PROJECT_WORKSPACE_CREATED'
export const PROJECT_WORKSPACE_UPDATED = 'PROJECT_WORKSPACE_UPDATED'

export const WORKSPACE_MEMBER_CREATED = 'WORKSPACE_MEMBER_CREATED'
export const WORKSPACE_MEMBER_DELETED = 'WORKSPACE_MEMBER_DELETED'
export const WORKSPACE_MEMBER_UPDATED = 'WORKSPACE_MEMBER_UPDATED'

export const PROJECT_MEMBER_CREATED = 'PROJECT_MEMBER_CREATED'
export const PROJECT_MEMBER_DELETED = 'PROJECT_MEMBER_DELETED'
export const PROJECT_MEMBER_UPDATED = 'PROJECT_MEMBER_UPDATED'
