# N.B. This is the legacy dockerfile, the one now used in development is
# snowpack/Dockerfile.dev

FROM node:12-alpine

VOLUME /concepts/frontend
WORKDIR /concepts/frontend

EXPOSE 3000

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["yarn && yarn start"]
