#!/bin/bash
if [[ "$1" == "prod" ]]; then
	docker-compose -f docker-compose.yml -f production.yml ${@:2}
elif [[ "$1" == "dev" ]]; then
	docker-compose --compatibility -f docker-compose.yml -f development.yml ${@:2}
else
	docker-compose --compatibility -f docker-compose.yml -f development.yml $@
fi
