const CONCEPT_CREATED = 'CONCEPT_CREATED'
const CONCEPT_UPDATED = 'CONCEPT_UPDATED'
const CONCEPT_DELETED = 'CONCEPT_DELETED'

const CONCEPT_LINK_CREATED = 'CONCEPT_LINK_CREATED'
const CONCEPT_LINK_DELETED = 'CONCEPT_LINK_DELETED'

const COURSE_CREATED = 'COURSE_CREATED'
const COURSE_UPDATED = 'COURSE_UPDATED'
const COURSE_DELETED = 'COURSE_DELETED'

const COURSE_LINK_CREATED = 'COURSE_LINK_CREATED'
const COURSE_LINK_UPDATED = 'COURSE_LINK_UPDATED'
const COURSE_LINK_DELETED = 'COURSE_LINK_DELETED'

const WORKSPACE_CREATED = 'WORKSPACE_CREATED'
const WORKSPACE_UPDATED = 'WORKSPACE_UPDATED'
const WORKSPACE_DELETED = 'WORKSPACE_DELETED'

module.exports = {
  CONCEPT_CREATED, CONCEPT_UPDATED, CONCEPT_DELETED,
  CONCEPT_LINK_CREATED, CONCEPT_LINK_DELETED,
  COURSE_CREATED, COURSE_UPDATED, COURSE_DELETED,
  COURSE_LINK_CREATED, COURSE_LINK_UPDATED, COURSE_LINK_DELETED,
  WORKSPACE_CREATED, WORKSPACE_UPDATED, WORKSPACE_DELETED
}