export const CONCEPT_CREATED = 'CONCEPT_CREATED'
export const CONCEPT_UPDATED = 'CONCEPT_UPDATED'
export const CONCEPT_DELETED = 'CONCEPT_DELETED'

export const CONCEPT_LINK_CREATED = 'CONCEPT_LINK_CREATED'
export const CONCEPT_LINK_DELETED = 'CONCEPT_LINK_DELETED'

export const COURSE_CREATED = 'COURSE_CREATED'
export const COURSE_UPDATED = 'COURSE_UPDATED'
export const COURSE_DELETED = 'COURSE_DELETED'

export const COURSE_LINK_CREATED = 'COURSE_LINK_CREATED'
export const COURSE_LINK_UPDATED = 'COURSE_LINK_UPDATED'
export const COURSE_LINK_DELETED = 'COURSE_LINK_DELETED'

export const WORKSPACE_CREATED = 'WORKSPACE_CREATED'
export const WORKSPACE_UPDATED = 'WORKSPACE_UPDATED'
export const WORKSPACE_DELETED = 'WORKSPACE_DELETED'

export const PROJECT_WORKSPACE_CLONED = 'PROJECT_WORKSPACE_CLONED'
export const PROJECT_WORKSPACE_DELETED = 'PROJECT_WORKSPACE_DELETED'
export const PROJECT_WORKSPACE_CREATED = 'PROJECT_WORKSPACE_CREATED'
export const PROJECT_WORKSPACE_UPDATED = 'PROJECT_WORKSPACE_UPDATED'